### ISSUE TITLE
Get fatal error: unexpected signal during runtime execution on Mac

### ISSUE THREAD

**Issue by technoblogy** [chilipeppr/serial-port-json-server#46]
Running serial-port-json-server on a MacBook Pro running High Sierra gives a fatal error:

```
Mac:~ david$ ./serial-port-json-server
1970/01/01 01:00:00 main.go:89: Version:1.86
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x95b02e1a00 pc=0x4108520]

goroutine 1 [running]:
runtime.throw(0x45515e0, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc82004fb90 sp=0xc82004fb78
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82004fbe0 sp=0xc82004fb90
sync.(*Pool).Get(0x46fba20, 0x0, 0x0)
	/usr/local/go/src/sync/pool.go:101 +0x40 fp=0xc82004fc30 sp=0xc82004fbe0
fmt.newPrinter(0x44d8d00)
	/usr/local/go/src/fmt/print.go:133 +0x27 fp=0xc82004fc70 sp=0xc82004fc30
fmt.Sprintln(0xc82004ff28, 0x2, 0x2, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:270 +0x28 fp=0xc82004fcc0 sp=0xc82004fc70
log.Println(0xc82004ff28, 0x2, 0x2)
	/usr/local/go/src/log/log.go:295 +0x35 fp=0xc82004fd08 sp=0xc82004fcc0
main.main()
	/Users/alden/Projects/proj82_go/src/serial-port-json-server/main.go:96 +0x3fa fp=0xc82004ff50 sp=0xc82004fd08
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc82004ffa0 sp=0xc82004ff50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82004ffa8 sp=0xc82004ffa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

Any suggestions?
Thanks, David

**Comment by chilipeppr** [comment]
Try latest version. 1.86 is old
